/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import UserFunctions.Login;
import java.awt.CardLayout;
import UserFunctions.Register;
import Workouts.NewRoutine;
import Workouts.wsrData;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AliFetanat
 */
public class MainFrame extends javax.swing.JFrame {

    CardLayout card = new CardLayout();
    wsrData dat;
    public ArrayList <wsrData> dataList;
    public MainFrame() {
        initComponents();

    }
    int setCount = 0;
    NewRoutine n;

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        Login = new javax.swing.JPanel();
        lnLoginBtn = new javax.swing.JButton();
        lnTitle = new javax.swing.JLabel();
        lnSubhead = new javax.swing.JLabel();
        lnLogintxt = new javax.swing.JLabel();
        lnPasswordfield = new javax.swing.JPasswordField();
        lnUserfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rrNamefield1 = new javax.swing.JTextField();
        rrPasswordfield1 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        rrCpasswordfield1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        rrUsernamefield1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lnLogintxt1 = new javax.swing.JLabel();
        rrRegisterbtn = new javax.swing.JButton();
        MainMenu = new javax.swing.JPanel();
        CreateRoutineBtn = new javax.swing.JButton();
        lnTitle2 = new javax.swing.JLabel();
        SavedRoutineBtn = new javax.swing.JButton();
        StartWorkoutBtn = new javax.swing.JButton();
        lnTitle3 = new javax.swing.JLabel();
        lnTitle4 = new javax.swing.JLabel();
        EditExercisesBtn = new javax.swing.JButton();
        ViewRecordsBtn = new javax.swing.JButton();
        CreateRoutine = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        lnTitle5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        mgName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        RoutineTable = new javax.swing.JTable();
        lnTitle8 = new javax.swing.JLabel();
        lnTitle9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        InputData = new javax.swing.JPanel();
        lnTitle6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        eTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        dTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        Routines = new javax.swing.JMenu();
        NewRoutine = new javax.swing.JMenuItem();
        SavedRoutines = new javax.swing.JMenuItem();
        Exercises = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        Records = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Main.setBackground(new java.awt.Color(255, 255, 255));
        Main.setForeground(new java.awt.Color(153, 153, 153));
        Main.setMaximumSize(new java.awt.Dimension(820, 479));
        Main.setLayout(new java.awt.CardLayout());

        Login.setBackground(new java.awt.Color(255, 255, 255));

        lnLoginBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lnLoginBtn.setForeground(new java.awt.Color(0, 153, 0));
        lnLoginBtn.setText("Login");
        lnLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnLoginBtnActionPerformed(evt);
            }
        });

        lnTitle.setFont(new java.awt.Font("Lucida Grande", 1, 30)); // NOI18N
        lnTitle.setForeground(new java.awt.Color(0, 153, 0));
        lnTitle.setText("Welcome To Track 'n Train");

        lnSubhead.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lnSubhead.setText("Login To Your Account ");

        lnLogintxt.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lnLogintxt.setText("Login:");

        lnPasswordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnPasswordfieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("Full Name:");
        jLabel6.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setText("Password:");

        rrNamefield1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        rrNamefield1.setMaximumSize(new java.awt.Dimension(55, 55));
        rrNamefield1.setMinimumSize(new java.awt.Dimension(55, 55));

        rrPasswordfield1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        rrPasswordfield1.setMaximumSize(new java.awt.Dimension(55, 55));
        rrPasswordfield1.setMinimumSize(new java.awt.Dimension(55, 55));

        jLabel8.setFont(new java.awt.Font("Tholoth", 1, 24)); // NOI18N
        jLabel8.setText("Register New Account");
        jLabel8.setMaximumSize(new java.awt.Dimension(55, 55));
        jLabel8.setMinimumSize(new java.awt.Dimension(55, 55));

        rrCpasswordfield1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        rrCpasswordfield1.setMaximumSize(new java.awt.Dimension(55, 55));
        rrCpasswordfield1.setMinimumSize(new java.awt.Dimension(55, 55));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel9.setText("Confirm Password:");
        jLabel9.setMaximumSize(new java.awt.Dimension(55, 55));
        jLabel9.setMinimumSize(new java.awt.Dimension(55, 55));

        rrUsernamefield1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        rrUsernamefield1.setMaximumSize(new java.awt.Dimension(55, 55));
        rrUsernamefield1.setMinimumSize(new java.awt.Dimension(55, 55));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setText("User Name:");
        jLabel10.setToolTipText("");

        lnLogintxt1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lnLogintxt1.setText("Password:");

        rrRegisterbtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        rrRegisterbtn.setForeground(new java.awt.Color(0, 153, 0));
        rrRegisterbtn.setText("Register");
        rrRegisterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rrRegisterbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lnUserfield, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lnPasswordfield, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LoginLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(lnLogintxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LoginLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(lnLogintxt))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LoginLayout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(lnLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rrPasswordfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(rrNamefield1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10)
                                    .addComponent(rrUsernamefield1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rrCpasswordfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rrRegisterbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lnSubhead)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 152, Short.MAX_VALUE))
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(lnTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lnTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnSubhead))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rrNamefield1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                        .addComponent(lnLogintxt)
                        .addGap(18, 18, 18)))
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rrUsernamefield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(5, 5, 5))
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addComponent(lnUserfield, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lnLogintxt1)))
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(rrPasswordfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LoginLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lnPasswordfield, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rrCpasswordfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rrRegisterbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(71, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                        .addComponent(lnLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );

        Main.add(Login, "Login");

        MainMenu.setBackground(new java.awt.Color(255, 255, 255));
        MainMenu.setPreferredSize(new java.awt.Dimension(820, 479));
        MainMenu.setRequestFocusEnabled(false);

        CreateRoutineBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        CreateRoutineBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/creates.png"))); // NOI18N
        CreateRoutineBtn.setText("Create Routine");
        CreateRoutineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateRoutineBtnActionPerformed(evt);
            }
        });

        lnTitle2.setFont(new java.awt.Font("Lucida Grande", 1, 30)); // NOI18N
        lnTitle2.setForeground(new java.awt.Color(0, 153, 0));
        lnTitle2.setText("Main Selection Menu");

        SavedRoutineBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        SavedRoutineBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/saved.png"))); // NOI18N
        SavedRoutineBtn.setText("Saved Routines");
        SavedRoutineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavedRoutineBtnActionPerformed(evt);
            }
        });

        StartWorkoutBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        StartWorkoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/start.png"))); // NOI18N
        StartWorkoutBtn.setText("Start Workout");
        StartWorkoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartWorkoutBtnActionPerformed(evt);
            }
        });

        lnTitle3.setFont(new java.awt.Font("Lucida Grande", 1, 22)); // NOI18N
        lnTitle3.setForeground(new java.awt.Color(0, 153, 0));
        lnTitle3.setText("Records & Lists");

        lnTitle4.setFont(new java.awt.Font("Lucida Grande", 1, 22)); // NOI18N
        lnTitle4.setForeground(new java.awt.Color(0, 153, 0));
        lnTitle4.setText("Workout & Routines");

        EditExercisesBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        EditExercisesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exercises.png"))); // NOI18N
        EditExercisesBtn.setText("Edit Exercises");
        EditExercisesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditExercisesBtnActionPerformed(evt);
            }
        });

        ViewRecordsBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ViewRecordsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exercises.png"))); // NOI18N
        ViewRecordsBtn.setText("View Records");
        ViewRecordsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRecordsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainMenuLayout = new javax.swing.GroupLayout(MainMenu);
        MainMenu.setLayout(MainMenuLayout);
        MainMenuLayout.setHorizontalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuLayout.createSequentialGroup()
                .addGap(96, 177, Short.MAX_VALUE)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MainMenuLayout.createSequentialGroup()
                        .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(MainMenuLayout.createSequentialGroup()
                                .addComponent(CreateRoutineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(SavedRoutineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lnTitle3))
                        .addGap(69, 69, 69)
                        .addComponent(StartWorkoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(MainMenuLayout.createSequentialGroup()
                        .addComponent(EditExercisesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(ViewRecordsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(222, 222, 222))))
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainMenuLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(lnTitle2))
                    .addGroup(MainMenuLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(lnTitle4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainMenuLayout.setVerticalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lnTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lnTitle4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateRoutineBtn)
                    .addComponent(SavedRoutineBtn)
                    .addComponent(StartWorkoutBtn))
                .addGap(47, 47, 47)
                .addComponent(lnTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditExercisesBtn)
                    .addComponent(ViewRecordsBtn))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        Main.add(MainMenu, "MainMenu");

        CreateRoutine.setBackground(new java.awt.Color(255, 255, 255));
        CreateRoutine.setForeground(new java.awt.Color(255, 255, 255));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cardio.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arms.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Shoulders.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/legs.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Abs.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        lnTitle5.setFont(new java.awt.Font("Lucida Grande", 1, 30)); // NOI18N
        lnTitle5.setForeground(new java.awt.Color(0, 153, 0));
        lnTitle5.setText("Create A Routine Plan");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel11.setText("Cardio");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel12.setText("  Arms    Shoulder    Back        Legs        Core");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Primary Muscle"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.setSelectionBackground(new java.awt.Color(0, 204, 51));
        Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Table);
        Table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (Table.getColumnModel().getColumnCount() > 0) {
            Table.getColumnModel().getColumn(0).setResizable(false);
            Table.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel13.setText("Exercise List For:");

        mgName.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        mgName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mgNameActionPerformed(evt);
            }
        });

        RoutineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Muscle Group", "Primary Muscle", "Exercise"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        RoutineTable.setSelectionBackground(new java.awt.Color(0, 255, 0));
        RoutineTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(RoutineTable);
        if (RoutineTable.getColumnModel().getColumnCount() > 0) {
            RoutineTable.getColumnModel().getColumn(0).setPreferredWidth(40);
        }

        lnTitle8.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lnTitle8.setForeground(new java.awt.Color(0, 153, 0));
        lnTitle8.setText("Click Muscle Group Or Cardio List For Exercise Lists");

        lnTitle9.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lnTitle9.setForeground(new java.awt.Color(0, 153, 0));
        lnTitle9.setText("Your Current Routine Plan");

        jButton2.setText("Remove ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton13.setText("Add To Routine");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Save Routine");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Start Routine");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreateRoutineLayout = new javax.swing.GroupLayout(CreateRoutine);
        CreateRoutine.setLayout(CreateRoutineLayout);
        CreateRoutineLayout.setHorizontalGroup(
            CreateRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateRoutineLayout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(lnTitle5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CreateRoutineLayout.createSequentialGroup()
                .addGroup(CreateRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateRoutineLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(CreateRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CreateRoutineLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CreateRoutineLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mgName, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CreateRoutineLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(CreateRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CreateRoutineLayout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateRoutineLayout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(CreateRoutineLayout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(CreateRoutineLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lnTitle8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CreateRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateRoutineLayout.createSequentialGroup()
                        .addComponent(jButton15)
                        .addGap(18, 18, 18)
                        .addComponent(jButton14)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateRoutineLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateRoutineLayout.createSequentialGroup()
                        .addComponent(lnTitle9, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        CreateRoutineLayout.setVerticalGroup(
            CreateRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateRoutineLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lnTitle5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(CreateRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CreateRoutineLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lnTitle8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(CreateRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CreateRoutineLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(CreateRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(CreateRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(CreateRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(CreateRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(mgName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateRoutineLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CreateRoutineLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lnTitle9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(CreateRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        Main.add(CreateRoutine, "card4");

        InputData.setBackground(new java.awt.Color(255, 255, 255));

        lnTitle6.setFont(new java.awt.Font("Lucida Grande", 1, 30)); // NOI18N
        lnTitle6.setForeground(new java.awt.Color(0, 153, 0));
        lnTitle6.setText("Workout Data");

        eTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Muscle Group", "Primary Muscle", "Exercise", "Done"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        eTable.setSelectionBackground(new java.awt.Color(0, 255, 0));
        eTable.getTableHeader().setReorderingAllowed(false);
        eTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eTableMouseClicked(evt);
            }
        });
        eTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                eTableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane4.setViewportView(eTable);
        if (eTable.getColumnModel().getColumnCount() > 0) {
            eTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            eTable.getColumnModel().getColumn(3).setResizable(false);
            eTable.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        dTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Set", "Weight", "Repetitions"
            }
        ));
        dTable.setColumnSelectionAllowed(true);
        dTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(dTable);
        dTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jButton1.setText("Add Set");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton7.setText("Add Note");

        jButton8.setText("Personal Best");

        javax.swing.GroupLayout InputDataLayout = new javax.swing.GroupLayout(InputData);
        InputData.setLayout(InputDataLayout);
        InputDataLayout.setHorizontalGroup(
            InputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputDataLayout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(lnTitle6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(InputDataLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InputDataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(14, 14, 14))
        );
        InputDataLayout.setVerticalGroup(
            InputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputDataLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lnTitle6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(InputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(InputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(68, 68, 68))
        );

        Main.add(InputData, "card5");

        getContentPane().add(Main, java.awt.BorderLayout.CENTER);

        Routines.setText("Routines");
        Routines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoutinesActionPerformed(evt);
            }
        });

        NewRoutine.setText("Create New");
        NewRoutine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewRoutineActionPerformed(evt);
            }
        });
        Routines.add(NewRoutine);

        SavedRoutines.setText("Saved Routines");
        Routines.add(SavedRoutines);

        MenuBar.add(Routines);

        Exercises.setText("Exercises");

        jMenuItem6.setText("Add");
        Exercises.add(jMenuItem6);

        jMenuItem7.setText("Remove");
        Exercises.add(jMenuItem7);

        MenuBar.add(Exercises);

        Records.setText("Records");
        MenuBar.add(Records);

        setJMenuBar(MenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewRoutineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewRoutineActionPerformed


    }//GEN-LAST:event_NewRoutineActionPerformed


    private void RoutinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoutinesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoutinesActionPerformed

    private void CreateRoutineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateRoutineBtnActionPerformed
        n = new NewRoutine();
        n.ClearTable();
        getContentPane().remove(MainMenu);
        getContentPane().add(MainMenu, CreateRoutine);
        card = (CardLayout) CreateRoutine.getLayout();

            card.show(MainMenu, "CreateRoutine");    }//GEN-LAST:event_CreateRoutineBtnActionPerformed

//GEN-FIRST:event_lnLoginBtnActionPerformed
    private void lnLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {
        String u = lnUserfield.getText();
        String p = lnPasswordfield.getText();
        Login l = new Login();
        l.Verify(u, p);

        if (l.passed == true) {
            getContentPane().remove(Login);
            getContentPane().add(Login, MainMenu);
            card = (CardLayout) MainMenu.getLayout();
            card.show(Login, "MainMenu");
        }

    }

//GEN-LAST:event_lnLoginBtnActionPerformed

    private void lnPasswordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnPasswordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnPasswordfieldActionPerformed

    private void rrRegisterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rrRegisterbtnActionPerformed

        String n, u, p, cp;
        n = rrNamefield1.getText();
        u = rrUsernamefield1.getText();

        p = rrPasswordfield1.getText();

        cp = rrCpasswordfield1.getText();

        Register x = new Register();
        x.Create(n, u, p, cp);

// TODO add your handling code here:
    }//GEN-LAST:event_rrRegisterbtnActionPerformed

    private void SavedRoutineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavedRoutineBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SavedRoutineBtnActionPerformed

    private void StartWorkoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartWorkoutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartWorkoutBtnActionPerformed

    private void EditExercisesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditExercisesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditExercisesBtnActionPerformed

    private void ViewRecordsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRecordsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewRecordsBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        n = new NewRoutine();
        mgName.setText("Cardio");
        n.QueeryList(this.Table, "Cardio");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        n = new NewRoutine();
        mgName.setText("Arms");
        n.QueeryList(this.Table, "Arms");


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        n = new NewRoutine();
        mgName.setText("Shoulder");
        n.QueeryList(this.Table, "Shoulder");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        n = new NewRoutine();
        mgName.setText("Legs");
        n.QueeryList(this.Table, "Legs");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        n = new NewRoutine();
        mgName.setText("Back");
        n.QueeryList(this.Table, "Back");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        n = new NewRoutine();
        mgName.setText("Core");
        n.QueeryList(this.Table, "Core");

    }//GEN-LAST:event_jButton12ActionPerformed

    private void mgNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mgNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mgNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        n.RemoveExercise(RoutineTable);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        n.addExercise(this.Table);
        n.OutputRoutineTable(this.RoutineTable);

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed

        JFrame frame = new JFrame();
        Object result = JOptionPane.showInputDialog(frame, "Enter Routine Name:");
        String name = (String) result;
        n.saveRoutine(name, RoutineTable);

    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed

        n = new NewRoutine();
        n.OutputRoutineTable(this.eTable);

        getContentPane().remove(CreateRoutine);
        getContentPane().add(CreateRoutine, InputData);
        card = (CardLayout) InputData.getLayout();
        card.show(CreateRoutine, "InputData");


    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        setCount++;
        DefaultTableModel model = (DefaultTableModel) dTable.getModel();
        model.addRow(new Object[]{setCount});
    }//GEN-LAST:event_jButton1ActionPerformed

    private void eTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eTableMouseClicked
        
        int row = eTable.rowAtPoint(evt.getPoint());
        String ex=(String)eTable.getValueAt(row, 2);
        String mu=(String)eTable.getValueAt(row, 0);
        String pr=(String)eTable.getValueAt(row, 1);
        
        n=new NewRoutine();
        
        n.addData(this.eTable, this.dTable, row,this.dat,this.dataList);
        
       /*  
        wsrData dat=new wsrData(ex,pr,mu);
        dataList.add(dat);

        System.out.println(dat);

        }
        System.out.println(dataList);
     
        */
       
        //n.getData(this.eTable, this.dTable, (String) this.eTable.getValueAt(row, 2));

       
    }//GEN-LAST:event_eTableMouseClicked

    private void eTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_eTableAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_eTableAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateRoutine;
    private javax.swing.JButton CreateRoutineBtn;
    private javax.swing.JButton EditExercisesBtn;
    private javax.swing.JMenu Exercises;
    private javax.swing.JPanel InputData;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel MainMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem NewRoutine;
    private javax.swing.JMenu Records;
    private javax.swing.JTable RoutineTable;
    private javax.swing.JMenu Routines;
    private javax.swing.JButton SavedRoutineBtn;
    private javax.swing.JMenuItem SavedRoutines;
    private javax.swing.JButton StartWorkoutBtn;
    public javax.swing.JTable Table;
    private javax.swing.JButton ViewRecordsBtn;
    public javax.swing.JTable dTable;
    private javax.swing.JTable eTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton lnLoginBtn;
    private javax.swing.JLabel lnLogintxt;
    private javax.swing.JLabel lnLogintxt1;
    private javax.swing.JPasswordField lnPasswordfield;
    private javax.swing.JLabel lnSubhead;
    private javax.swing.JLabel lnTitle;
    private javax.swing.JLabel lnTitle2;
    private javax.swing.JLabel lnTitle3;
    private javax.swing.JLabel lnTitle4;
    private javax.swing.JLabel lnTitle5;
    private javax.swing.JLabel lnTitle6;
    private javax.swing.JLabel lnTitle8;
    private javax.swing.JLabel lnTitle9;
    private javax.swing.JTextField lnUserfield;
    private javax.swing.JTextField mgName;
    private javax.swing.JPasswordField rrCpasswordfield1;
    private javax.swing.JTextField rrNamefield1;
    private javax.swing.JPasswordField rrPasswordfield1;
    private javax.swing.JButton rrRegisterbtn;
    private javax.swing.JTextField rrUsernamefield1;
    // End of variables declaration//GEN-END:variables
}
